#!/bin/bash

service mysql start

mariadb -v -u root << EOF
"CREATE DATABASE IF NOT EXISTS $MARIADB_NAME ;"

"ALTER USER 'root'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PSWD' ;"

"CREATE USER IF NOT EXISTS '$MARIADB_ADMIN_USER'@'%' IDENTIFIED BY '$MARIADB_ROOT_PSWD' ;"
"GRANT ALL PRIVILEGES ON $MARIADB_ADMIN_NAME.* TO '$MARIADB_ADMIN_USER'@'%' ;"
"ALTER USER '$MARIADB_ADMIN_NAME'@'%' REQUIRE SSL;"

"FLUSH PRIVILEGES;"
EOF

sleep 16

service mariadb stop

exec mysqld_safe
