#!/bin/bash

set -x
service mariadb start

mariadb -e "CREATE DATABASE IF NOT EXISTS $MARIADB_DBNAME ;"
mariadb -e "CREATE USER IF NOT EXISTS '$MARIADB_ADMIN_USER'@'%' IDENTIFIED BY '$MARIADB_ROOT_PSWD' ;"
mariadb -e "GRANT ALL PRIVILEGES ON $MARIADB_DBNAME.* TO '$MARIADB_ADMIN_USER'@'%' IDENTIFIED BY '$MARIADB_ROOT_PSWD' ;"
mariadb -e "GRANT ALL PRIVILEGES ON $MARIADB_DBNAME.* TO 'root'@'%' IDENTIFIED BY '$MARIADB_ROOT_PSWD' ;"
mariadb -e "SET PASSWORD FOR 'root'@'%' = PASSWORD('$MARIADB_ROOT_PSWD') ;"
mariadb -e "FLUSH PRIVILEGES;"

service mariadb stop

exec mysqld_safe
